// next.config.mjs — OnlineKazino.com
//
// Static generation by default (no SSR). Redirects loaded from
// data/redirects.json so they stay in lockstep with content imports.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const redirectsRaw = JSON.parse(
  readFileSync(resolve(__dirname, 'data/redirects.json'), 'utf8'),
);

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  trailingSlash: true,

  // We mostly serve static HTML; image optimization runs at build/edge for hero
  // and operator-logo assets.
  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: [
      // Operator logos & marketing assets we ingest from official sources
      { protocol: 'https', hostname: '**.onlinekazino.com' },
      { protocol: 'https', hostname: '**.optibet.lv' },
      { protocol: 'https', hostname: '**.olybet.lv' },
      { protocol: 'https', hostname: '**.lvbet.lv' },
      { protocol: 'https', hostname: '**.klondaika.lv' },
      { protocol: 'https', hostname: '**.laimz.lv' },
      { protocol: 'https', hostname: '**.iaui.gov.lv' },
    ],
  },

  // Legacy WP URLs → new IA. Two sources:
  //
  // 1. ID-based query redirects from data/redirects.json (generated by
  //    scripts/import-wp.mjs from <wp:post_id>). These cover ?p= and
  //    ?post_type=casino&p= patterns.
  // 2. Path-based redirects for pretty WP permalinks observed on the live
  //    site (e.g. /apskati/optibet/, /labakie-kazino/). These were never in
  //    the WP export's structured fields — extracted by inspecting the live
  //    site and audited in docs/CONTENT_AUDIT.md.
  //
  // Note: Next.js parses `source` with path-to-regexp, where `?` is a
  // reserved "optional" modifier. Query-string sources must use the `has`
  // array form.
  async redirects() {
    const idBased = redirectsRaw.map((r) => {
      const u = new URL(r.from, 'https://x.example');
      const has = Array.from(u.searchParams.entries()).map(([key, value]) => ({
        type: 'query',
        key,
        value,
      }));
      return {
        source: u.pathname || '/',
        ...(has.length > 0 && { has }),
        destination: r.to,
        permanent: r.permanent !== false,
      };
    });

    const pathBased = [
      // Casino reviews — live site uses /apskati/{slug}/
      { source: '/apskati/optibet/',          destination: '/kazino/optibet/',          permanent: true },
      { source: '/apskati/klondaika-kazino/', destination: '/kazino/klondaika-kazino/', permanent: true },
      { source: '/apskati/laimz/',            destination: '/kazino/laimz/',            permanent: true },
      { source: '/apskati/:slug/',            destination: '/kazino/:slug/',            permanent: true },

      // Live taxonomy / hub URLs → new IA equivalents
      { source: '/labakie-kazino/',         destination: '/kazino/',                       permanent: true },
      { source: '/arzemju-kazino/',         destination: '/kazino/',                       permanent: true },
      { source: '/jauni-kazino/',           destination: '/kazino/',                       permanent: true },
      { source: '/live-kazino/',            destination: '/speles/live-kazino/',           permanent: true },
      { source: '/mobilie-kazino/',         destination: '/kazino/',                       permanent: true },
      { source: '/kazino-speles/',          destination: '/speles/',                       permanent: true },
      { source: '/azartspeles/',            destination: '/speles/',                       permanent: true },
      { source: '/spelu-automati/',         destination: '/speles/spelu-automati/',        permanent: true },
      { source: '/pokers/',                 destination: '/speles/pokers/',                permanent: true },
      { source: '/video-pokers/',           destination: '/speles/pokers/',                permanent: true },
      { source: '/blackjack/',              destination: '/speles/blackjack/',             permanent: true },
      { source: '/rulete/',                 destination: '/speles/rulete/',                permanent: true },
      { source: '/bingo/',                  destination: '/speles/',                       permanent: true },
      { source: '/baccarat/',               destination: '/speles/baccarat/',              permanent: true },
      { source: '/bezriska-griezieni/',     destination: '/bonusi/bezmaksas-griezieni/',   permanent: true },
      { source: '/zinas/',                  destination: '/raksti/',                       permanent: true },
      { source: '/online-kazino-jaunumi/',  destination: '/raksti/',                       permanent: true },
      { source: '/category/zinas/',         destination: '/raksti/',                       permanent: true },
      { source: '/category/:slug/',         destination: '/raksti/kategorija/:slug/',      permanent: true },

      // Static page slug remaps
      { source: '/privatuma-politika-2/',     destination: '/privatuma-politika/',     permanent: true },
      { source: '/sikdatnes-politika/',       destination: '/sikdatnes/',              permanent: true },
      { source: '/ka-mes-izvertejam-kazino/', destination: '/metodologija/',           permanent: true },

      // Game CPT — discarded, fold into slot-machines hub
      { source: '/game/:slug/',          destination: '/speles/spelu-automati/', permanent: true },
      { source: '/game-category/:slug/', destination: '/speles/spelu-automati/', permanent: true },
    ];

    return [...idBased, ...pathBased];
  },

  // Strict-Transport-Security and other safety headers.
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=()',
          },
          {
            key: 'Strict-Transport-Security',
            value: 'max-age=63072000; includeSubDomains; preload',
          },
        ],
      },
    ];
  },
};

export default nextConfig;
